Repository AY2021S1-CS2103T-W15-1/tp, pull requests merged in 2020-10, with the labels that each got.

#40 List for v1.2
  src/main/java/seedu/medmoriser/ui/QuestionSetCard.java
  src/main/resources/view/QuestionSetListCard.fxml
Labels: enhancement

#42 Rename list success message
  src/main/java/seedu/medmoriser/logic/commands/ListCommand.java
  src/test/java/seedu/medmoriser/logic/commands/ListCommandTest.java
Labels: Refactor, Testing

#44 Rename more methods that contain QuestionSet to QAndA
  src/main/java/seedu/medmoriser/commons/core/Messages.java
  src/main/java/seedu/medmoriser/logic/LogicManager.java
  src/main/java/seedu/medmoriser/logic/commands/DeleteCommand.java
  src/main/java/seedu/medmoriser/logic/commands/EditCommand.java
  src/main/java/seedu/medmoriser/logic/commands/FindCommand.java
  src/main/java/seedu/medmoriser/logic/commands/ListCommand.java
  src/main/java/seedu/medmoriser/model/Medmoriser.java
  src/main/java/seedu/medmoriser/model/Model.java
  src/main/java/seedu/medmoriser/model/ModelManager.java
  src/main/java/seedu/medmoriser/model/ReadOnlyMedmoriser.java
  src/main/java/seedu/medmoriser/storage/JsonSerializableMedmoriser.java
  src/test/java/seedu/medmoriser/logic/LogicManagerTest.java
  src/test/java/seedu/medmoriser/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/medmoriser/logic/commands/AddCommandTest.java
  src/test/java/seedu/medmoriser/logic/commands/CommandTestUtil.java
  src/test/java/seedu/medmoriser/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/medmoriser/logic/commands/EditCommandTest.java
  src/test/java/seedu/medmoriser/logic/commands/FindCommandTest.java
  src/test/java/seedu/medmoriser/logic/commands/ListCommandTest.java
  src/test/java/seedu/medmoriser/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/medmoriser/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/medmoriser/logic/parser/MedmoriserParserTest.java
  src/test/java/seedu/medmoriser/logic/parser/ParserUtilTest.java
  src/test/java/seedu/medmoriser/model/MedmoriserTest.java
  src/test/java/seedu/medmoriser/model/ModelManagerTest.java
  src/test/java/seedu/medmoriser/testutil/TestUtil.java
  src/test/java/seedu/medmoriser/testutil/TypicalIndexes.java
Labels: Refactor, Testing, enhancement

#46 Change title of app
  src/main/resources/view/MainWindow.fxml
Labels: bug

#54 Change URL of HelpCommand window
  src/main/java/seedu/medmoriser/ui/HelpWindow.java
Labels: bug

#53 Change ClearCommand success message
  src/main/java/seedu/medmoriser/logic/commands/ClearCommand.java
Labels: bug

#55 Search feature
  docs/UserGuide.md
  src/main/java/seedu/medmoriser/logic/commands/FindCommand.java
  src/main/java/seedu/medmoriser/logic/parser/FindCommandParser.java
  src/main/java/seedu/medmoriser/model/qanda/Answer.java
  src/main/java/seedu/medmoriser/model/qanda/AnswerContainsKeywordsPredicate.java
  src/main/java/seedu/medmoriser/model/qanda/QAndAContainsKeywordsPredicate.java
  src/main/java/seedu/medmoriser/model/qanda/TagContainsKeywordsPredicate.java
  src/main/java/seedu/medmoriser/storage/JsonAdaptedQAndA.java
  src/main/java/seedu/medmoriser/ui/QuestionSetCard.java
  src/test/java/seedu/medmoriser/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/medmoriser/logic/parser/MedmoriserParserTest.java
  src/test/java/seedu/medmoriser/testutil/QuestionSetUtil.java
Labels: enhancement

#57 Add ability to hide answers
  docs/UserGuide.md
  src/main/java/seedu/medmoriser/logic/commands/CommandResult.java
  src/main/java/seedu/medmoriser/logic/commands/ListCommand.java
  src/main/java/seedu/medmoriser/logic/parser/ListCommandParser.java
  src/main/java/seedu/medmoriser/logic/parser/MedmoriserParser.java
  src/main/java/seedu/medmoriser/ui/MainWindow.java
  src/main/java/seedu/medmoriser/ui/QuestionSetCard.java
  src/main/java/seedu/medmoriser/ui/QuestionSetListPanel.java
  src/test/java/seedu/medmoriser/logic/LogicManagerTest.java
  src/test/java/seedu/medmoriser/logic/commands/ListCommandTest.java
  src/test/java/seedu/medmoriser/logic/parser/MedmoriserParserTest.java
Labels: enhancement

#58 Add testcases for Find command
  build.gradle
  src/main/java/seedu/medmoriser/logic/LogicManager.java
  src/test/java/seedu/medmoriser/logic/commands/FindCommandTest.java
  src/test/java/seedu/medmoriser/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/medmoriser/model/qanda/AnswerContainsKeywordPredicateTest.java
  src/test/java/seedu/medmoriser/model/qanda/QAndAContainsKeywordPredicateTest.java
  src/test/java/seedu/medmoriser/model/qanda/QuestionContainsKeywordsPredicateTest.java
  src/test/java/seedu/medmoriser/model/qanda/TagContainsKeywordPredicateTest.java
Labels: Testing

#60 Add testing for ListCommand
  src/main/java/seedu/medmoriser/logic/commands/ListCommand.java
  src/test/java/seedu/medmoriser/logic/commands/ListCommandTest.java
  src/test/java/seedu/medmoriser/logic/parser/ListCommandParserTest.java
Labels: Testing

#62 Quiz feature
  build.gradle
  src/main/java/seedu/medmoriser/commons/core/Messages.java
  src/main/java/seedu/medmoriser/logic/commands/AddCommand.java
  src/main/java/seedu/medmoriser/logic/commands/AnswerCommand.java
  src/main/java/seedu/medmoriser/logic/commands/ClearCommand.java
  src/main/java/seedu/medmoriser/logic/commands/DeleteCommand.java
  src/main/java/seedu/medmoriser/logic/commands/EditCommand.java
  src/main/java/seedu/medmoriser/logic/commands/ExitQuizCommand.java
  src/main/java/seedu/medmoriser/logic/commands/FindCommand.java
  src/main/java/seedu/medmoriser/logic/commands/HelpCommand.java
  src/main/java/seedu/medmoriser/logic/commands/ListCommand.java
  src/main/java/seedu/medmoriser/logic/commands/QuizCommand.java
  src/main/java/seedu/medmoriser/logic/parser/AddCommandParser.java
  src/main/java/seedu/medmoriser/logic/parser/AnswerCommandParser.java
  src/main/java/seedu/medmoriser/logic/parser/MedmoriserParser.java
  src/main/java/seedu/medmoriser/logic/parser/QuizCommandParser.java
Labels: enhancement

#65 Remove space for find and quiz parameters.
  src/main/java/seedu/medmoriser/logic/commands/AnswerCommand.java
  src/main/java/seedu/medmoriser/logic/commands/ExitQuizCommand.java
  src/main/java/seedu/medmoriser/logic/commands/QuizCommand.java
  src/main/java/seedu/medmoriser/logic/parser/FindCommandParser.java
  src/main/java/seedu/medmoriser/logic/parser/QuizCommandParser.java
  src/test/java/seedu/medmoriser/logic/parser/FindCommandParserTest.java
Labels: Refactor, enhancement

#68 Update to Find command
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/FindSequenceDiagram.puml
  docs/diagrams/style.puml
  docs/images/FindSequenceDiagram.png
  src/main/java/seedu/medmoriser/logic/commands/FindCommand.java
  src/main/java/seedu/medmoriser/logic/parser/FindCommandParser.java
  src/main/java/seedu/medmoriser/model/qanda/QAndAContainsKeywordsPredicate.java
  src/main/java/seedu/medmoriser/model/qanda/QuestionContainsKeywordsPredicate.java
  src/main/java/seedu/medmoriser/model/qanda/TagContainsKeywordsPredicate.java
  src/test/java/seedu/medmoriser/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/medmoriser/logic/parser/MedmoriserParserTest.java
  src/test/java/seedu/medmoriser/model/qanda/TagContainsKeywordPredicateTest.java
Labels: Developer's Guide, Testing, bug, documentation, enhancement

#69 Fix answer hiding bug
  src/main/java/seedu/medmoriser/logic/commands/CommandResult.java
Labels: bug

#71 Remove Phone and Email instances, refactor TypicalQAndA
  src/main/java/seedu/medmoriser/logic/commands/AddCommand.java
  src/main/java/seedu/medmoriser/logic/commands/EditCommand.java
  src/main/java/seedu/medmoriser/logic/parser/AddCommandParser.java
  src/main/java/seedu/medmoriser/logic/parser/CliSyntax.java
  src/main/java/seedu/medmoriser/logic/parser/EditCommandParser.java
  src/main/java/seedu/medmoriser/logic/parser/ParserUtil.java
  src/main/java/seedu/medmoriser/model/qanda/Email.java
  src/main/java/seedu/medmoriser/model/qanda/Phone.java
  src/main/java/seedu/medmoriser/model/qanda/QAndA.java
  src/main/java/seedu/medmoriser/model/util/SampleDataUtil.java
  src/main/java/seedu/medmoriser/storage/JsonAdaptedQAndA.java
  src/test/data/JsonMedmoriserStorageTest/invalidAndValidQAndAMedmoriser.json
  src/test/data/JsonMedmoriserStorageTest/invalidQAndAMedmoriser.json
  src/test/data/JsonSerializableMedmoriserTest/duplicateQAndAMedmoriser.json
  src/test/data/JsonSerializableMedmoriserTest/invalidQAndAMedmoriser.json
  src/test/data/JsonSerializableMedmoriserTest/typicalQAndAsMedmoriser.json
  src/test/java/seedu/medmoriser/logic/LogicManagerTest.java
  src/test/java/seedu/medmoriser/logic/commands/CommandTestUtil.java
  src/test/java/seedu/medmoriser/logic/commands/EditCommandTest.java
  src/test/java/seedu/medmoriser/logic/commands/EditQAndADescriptorTest.java
  src/test/java/seedu/medmoriser/logic/commands/FindCommandTest.java
  src/test/java/seedu/medmoriser/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/medmoriser/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/medmoriser/logic/parser/ParserUtilTest.java
  src/test/java/seedu/medmoriser/model/MedmoriserTest.java
  src/test/java/seedu/medmoriser/model/ModelManagerTest.java
  src/test/java/seedu/medmoriser/model/qanda/AnswerContainsKeywordPredicateTest.java
  src/test/java/seedu/medmoriser/model/qanda/EmailTest.java
  src/test/java/seedu/medmoriser/model/qanda/PhoneTest.java
  src/test/java/seedu/medmoriser/model/qanda/QAndATest.java
  src/test/java/seedu/medmoriser/model/qanda/QuestionContainsKeywordsPredicateTest.java
  src/test/java/seedu/medmoriser/model/qanda/UniqueQAndAListTest.java
  src/test/java/seedu/medmoriser/storage/JsonAdaptedQAndATest.java
  src/test/java/seedu/medmoriser/storage/JsonMedmoriserStorageTest.java
  src/test/java/seedu/medmoriser/testutil/EditQAndADescriptorBuilder.java
  src/test/java/seedu/medmoriser/testutil/QAndABuilder.java
  src/test/java/seedu/medmoriser/testutil/QAndAUtil.java
  src/test/java/seedu/medmoriser/testutil/TypicalQAndA.java
Labels: Refactor, Testing

#72 Update UG for consistency
  docs/UserGuide.md
Labels: documentation

#74 Fix UG formatting
  docs/UserGuide.md
Labels: documentation

#73 Implement testing for quiz and update QuizCommand class
  src/main/java/seedu/medmoriser/logic/commands/ExitQuizCommand.java
  src/main/java/seedu/medmoriser/logic/commands/QuizCommand.java
  src/main/java/seedu/medmoriser/logic/parser/QuizCommandParser.java
  src/test/java/seedu/medmoriser/logic/commands/CommandTestUtil.java
  src/test/java/seedu/medmoriser/logic/commands/ExitQuizCommandTest.java
  src/test/java/seedu/medmoriser/logic/commands/QuizCommandTest.java
  src/test/java/seedu/medmoriser/logic/parser/QuizCommandParserTest.java
Labels: Testing, enhancement

#75 Find command update
  src/main/java/seedu/medmoriser/logic/commands/FindCommand.java
  src/main/java/seedu/medmoriser/logic/parser/FindCommandParser.java
  src/main/java/seedu/medmoriser/model/qanda/AnswerContainsKeywordsPredicate.java
  src/main/java/seedu/medmoriser/model/qanda/QuestionContainsKeywordsPredicate.java
  src/test/java/seedu/medmoriser/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/medmoriser/logic/parser/QuizCommandParserTest.java
Labels: bug

#78 Add 'delete' feature into DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/DeleteActivityDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/EditSequenceDiagram.puml
  docs/images/DeleteActivityDiagram.png
  docs/images/DeleteSequenceDiagram.png
Labels: Developer's Guide

#79 Update DG and UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/FindActivityDiagram.puml
  docs/images/FindActivityDiagram.png
Labels: documentation

#77 GUI v1.3
  src/main/java/seedu/medmoriser/logic/commands/AnswerCommand.java
  src/main/java/seedu/medmoriser/logic/commands/ExitQuizCommand.java
  src/main/java/seedu/medmoriser/logic/commands/FindCommand.java
  src/main/java/seedu/medmoriser/logic/commands/ListCommand.java
  src/main/java/seedu/medmoriser/logic/commands/QuizCommand.java
  src/main/java/seedu/medmoriser/model/qanda/QAndA.java
  src/main/java/seedu/medmoriser/ui/QuestionSetListPanel.java
  src/main/java/seedu/medmoriser/ui/QuizCard.java
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/QuestionSetListCard.fxml
  src/main/resources/view/QuestionSetListPanel.fxml
  src/main/resources/view/QuizCard.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/StatusBarFooter.fxml
Labels: enhancement

#81 Update intro and find command
  docs/UserGuide.md
  docs/images/FindContext.PNG
  docs/images/FindResult.PNG
Labels: User Guide, documentation

#84 Add implementation details for list command
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ListActivityDiagram.puml
  docs/diagrams/ListSequenceDiagram.puml
  docs/diagrams/style.puml
  docs/images/ListActivityDiagram.png
  docs/images/ListSequenceDiagram.png
  src/main/java/seedu/medmoriser/ui/QuestionSetListPanel.java
Labels: Developer's Guide

#83 Update user guide 'delete' and 'edit' feature, update quiz GUI
  docs/UserGuide.md
  src/main/java/seedu/medmoriser/ui/QuizCard.java
  src/main/resources/view/QuizCard.fxml
Labels: User Guide

#82 V1.3 ug update
  docs/UserGuide.md
Labels: bug

#85 Update UG and DG, fix bug in QuizCommandParser
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/QuizContext.png
  docs/images/QuizResult.png
  src/main/java/seedu/medmoriser/logic/parser/QuizCommandParser.java
  src/test/java/seedu/medmoriser/logic/parser/QuizCommandParserTest.java
Labels: Developer's Guide, User Guide, bug

#89 Change sample data and json filenames
  src/main/java/seedu/medmoriser/MainApp.java
  src/main/java/seedu/medmoriser/commons/core/LogsCenter.java
  src/main/java/seedu/medmoriser/model/Medmoriser.java
  src/main/java/seedu/medmoriser/model/Model.java
  src/main/java/seedu/medmoriser/model/ModelManager.java
  src/main/java/seedu/medmoriser/model/ReadOnlyMedmoriser.java
  src/main/java/seedu/medmoriser/model/UserPrefs.java
  src/main/java/seedu/medmoriser/model/util/SampleDataUtil.java
  src/main/java/seedu/medmoriser/storage/JsonMedmoriserStorage.java
  src/main/java/seedu/medmoriser/storage/JsonSerializableMedmoriser.java
  src/main/java/seedu/medmoriser/storage/MedmoriserStorage.java
  src/main/java/seedu/medmoriser/storage/Storage.java
  src/test/java/seedu/medmoriser/storage/JsonUserPrefsStorageTest.java
Labels: Refactor

#92 Update delete and edit features in UserGuide
  docs/UserGuide.md
  docs/images/DeleteContext.png
  docs/images/DeleteResult.png
  docs/images/EditContext.png
  docs/images/EditResult.png
Labels: User Guide

#91 Update how to use the guide and list feature
  docs/UserGuide.md
  docs/images/ListCommand.png
Labels: User Guide, documentation

#93 V1.3 ug update
  docs/UserGuide.md
Labels: User Guide

#90 Update Ui.png
  docs/images/Ui.png
  src/test/data/JsonMedmoriserStorageTest/invalidQAndAMedmoriser.json
Labels: documentation

#94 Update DG Quiz sequence and activity diagram
  docs/DeveloperGuide.md
  docs/diagrams/QuizActivityDiagram.puml
  docs/diagrams/QuizSequenceDiagram.puml
  docs/images/QuizActivityDiagram.png
  docs/images/QuizSequenceDiagram.png
Labels: Developer's Guide
