Repository AY2021S1-CS2103T-W15-1/tp, pull requests merged in 2020-11, with the labels that each got.

#136 Show answer after certain commands
  src/main/java/seedu/medmoriser/logic/commands/AddCommand.java
  src/main/java/seedu/medmoriser/logic/commands/EditCommand.java
  src/main/java/seedu/medmoriser/logic/commands/FindCommand.java
  src/test/java/seedu/medmoriser/logic/commands/AddCommandTest.java
  src/test/java/seedu/medmoriser/logic/commands/EditCommandTest.java
  src/test/java/seedu/medmoriser/logic/commands/FindCommandTest.java
Labels: bug

#137 Edit add command example and find command example and parameters
  src/main/java/seedu/medmoriser/logic/commands/AddCommand.java
  src/main/java/seedu/medmoriser/logic/commands/FindCommand.java
Labels: bug

#134 Change word choice for clear command in User Guide
  docs/UserGuide.md
Labels: User Guide

#138 Find command bug
  src/main/java/seedu/medmoriser/model/qanda/AnswerContainsKeywordsPredicate.java
  src/main/java/seedu/medmoriser/model/qanda/QAndAContainsKeywordsPredicate.java
  src/main/java/seedu/medmoriser/model/qanda/QuestionContainsKeywordsPredicate.java
Labels: bug

#140 Delete command message
  src/main/java/seedu/medmoriser/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/medmoriser/logic/parser/ParserUtil.java
  src/main/java/seedu/medmoriser/model/qanda/TagContainsKeywordsPredicate.java
  src/test/java/seedu/medmoriser/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/medmoriser/logic/parser/ParserUtilTest.java
  src/test/java/seedu/medmoriser/model/qanda/TagContainsKeywordPredicateTest.java
Labels: bug

#142 Add tags to QAndA string only if present
  src/main/java/seedu/medmoriser/model/qanda/QAndA.java
  src/preferences.json
Labels: bug

#146 Change Q&A to QAndA in User Guide for standardisation
  docs/UserGuide.md
Labels: User Guide, bug

#141 Rename exitquiz to endquiz, reference issue #117
  docs/UserGuide.md
  src/main/java/seedu/medmoriser/logic/commands/EndQuizCommand.java
  src/main/java/seedu/medmoriser/logic/parser/MedmoriserParser.java
  src/test/java/seedu/medmoriser/logic/commands/EndQuizCommandTest.java
  src/test/java/seedu/medmoriser/logic/commands/QuizCommandTest.java
Labels: bug

#147 #112 remove function to quiz based on answer
  docs/UserGuide.md
  src/main/java/seedu/medmoriser/logic/commands/QuizCommand.java
  src/main/java/seedu/medmoriser/logic/parser/QuizCommandParser.java
  src/test/java/seedu/medmoriser/logic/parser/QuizCommandParserTest.java
Labels: bug

#145 Change isSameQAndA to check for question field only
  src/main/java/seedu/medmoriser/model/qanda/QAndA.java
  src/main/java/seedu/medmoriser/model/qanda/UniqueQAndAList.java
  src/test/java/seedu/medmoriser/model/qanda/QAndATest.java
Labels: bug

#143 Remove F1 from help menu
  src/main/java/seedu/medmoriser/ui/MainWindow.java
Labels: bug

#148 Added PPP
  docs/team/yongmingyang.md
Labels: documentation

#144 Throw error when user tries to answer quiz after answering once
  src/main/java/seedu/medmoriser/logic/commands/AnswerCommand.java
  src/main/java/seedu/medmoriser/logic/commands/EndQuizCommand.java
  src/main/java/seedu/medmoriser/logic/commands/QuizCommand.java
  src/main/java/seedu/medmoriser/model/qanda/QAndA.java
Labels: bug

#152 Add NextCommand for continuous quizzing
  src/main/java/seedu/medmoriser/logic/commands/AnswerCommand.java
  src/main/java/seedu/medmoriser/logic/commands/CommandResult.java
  src/main/java/seedu/medmoriser/logic/commands/NextCommand.java
  src/main/java/seedu/medmoriser/logic/commands/QuizCommand.java
  src/main/java/seedu/medmoriser/logic/parser/MedmoriserParser.java
  src/main/java/seedu/medmoriser/logic/parser/NextCommandParser.java
  src/main/java/seedu/medmoriser/ui/QuestionSetListPanel.java
Labels: enhancement

#150 Implement PPP
  docs/team/joshruien.md
Labels: documentation

#149 Add PPP
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/tengjianling.md
Labels: documentation

#151 Add personal portfolio page
  docs/team/jonfoocy.md
  docs/team/yongmingyang.md
Labels: documentation

#154 Bug fix for questions and answers similar to prefix.
  src/main/java/seedu/medmoriser/logic/commands/AddCommand.java
  src/main/java/seedu/medmoriser/logic/commands/EditCommand.java
  src/main/java/seedu/medmoriser/logic/parser/AddCommandParser.java
  src/main/java/seedu/medmoriser/logic/parser/EditCommandParser.java
  src/test/java/seedu/medmoriser/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/medmoriser/logic/parser/EditCommandParserTest.java
Labels: Testing, bug

#155 #125 missing answer example
  docs/UserGuide.md
  src/main/java/seedu/medmoriser/model/qanda/QAndA.java
  src/main/java/seedu/medmoriser/ui/QuestionSetListPanel.java
Labels: User Guide

#153 Add 'next' command into UG
  docs/UserGuide.md
Labels: User Guide

#156 Standardise UG format and fix NextCommand bug
  docs/UserGuide.md
  src/main/java/seedu/medmoriser/logic/commands/NextCommand.java
Labels: User Guide, bug

#158 fixed tag wrap text
  docs/UserGuide.md
  docs/images/AddCommandEg1.png
  docs/images/AddCommandEg2.png
  docs/images/AddCommandEg3.png
  docs/images/AddCommandEg4.png
  src/main/java/seedu/medmoriser/ui/QuestionSetCard.java
  src/main/resources/view/QuestionSetListCard.fxml
Labels: GUI, bug

#157 Add AnswerCommandTest and AnswerCommandParserTest
  src/main/java/seedu/medmoriser/logic/commands/AnswerCommand.java
  src/main/java/seedu/medmoriser/logic/commands/QuizCommand.java
  src/main/java/seedu/medmoriser/logic/parser/AnswerCommandParser.java
  src/test/java/seedu/medmoriser/logic/commands/AnswerCommandTest.java
  src/test/java/seedu/medmoriser/logic/parser/AnswerCommandParserTest.java
Labels: Testing

#160 Nextcommand testing
  src/main/java/seedu/medmoriser/commons/core/Messages.java
  src/main/java/seedu/medmoriser/logic/parser/NextCommandParser.java
  src/test/java/seedu/medmoriser/logic/commands/NextCommandTest.java
  src/test/java/seedu/medmoriser/logic/commands/QuizCommandTest.java
Labels: Testing

#161 Fixed GUI for next command
  src/main/java/seedu/medmoriser/logic/commands/AnswerCommand.java
  src/main/java/seedu/medmoriser/logic/commands/NextCommand.java
  src/main/java/seedu/medmoriser/ui/QuizCard.java
  src/main/resources/view/QuizCard.fxml
Labels: GUI

#159 restructure DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: Developer's Guide

#162 Fixed empty bubbles problems, moved Command Box to the bottom
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/QuizCard.fxml
  src/main/resources/view/ResultDisplay.fxml
Labels: GUI

#164 Add table of contents to user guide
  docs/UserGuide.md
Labels: User Guide

#163 Update PPP and add 'Appendix: Effort' into DG
  docs/DeveloperGuide.md
  docs/team/tengjianling.md
Labels: Developer's Guide, documentation

#165 UI
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/QuizCard.fxml
  src/main/resources/view/ResultDisplay.fxml
Labels: GUI

#166 edit DG quiz activity diagram
  docs/diagrams/QuizActivityDiagram.puml
  docs/images/QuizActivityDiagram.png
Labels: Developer's Guide

#167 Update DG
  docs/DeveloperGuide.md
  docs/SettingUp.md
Labels: Developer's Guide

#169 Edit PPP
  docs/team/joshruien.md
Labels: documentation

#170 Update UG for currency and consistency
  docs/UserGuide.md
Labels: User Guide

#172 Ui
  docs/tutorials/AddRemark.md
  src/main/java/seedu/medmoriser/MainApp.java
  src/main/java/seedu/medmoriser/ui/UiManager.java
  src/main/resources/images/HealthEmoticon.PNG
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/QuizCard.fxml
Labels: GUI

#171 Quizcommandparser bugfix
  src/main/java/seedu/medmoriser/logic/parser/QuizCommandParser.java
  src/test/java/seedu/medmoriser/logic/parser/QuizCommandParserTest.java
Labels: bug

#173 Update PPP
  docs/team/tengjianling.md
Labels: documentation

#176 DG add TOC and edit architecture diagrams
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
Labels: Developer's Guide

#174 Change app icon
  src/main/java/seedu/medmoriser/ui/UiManager.java
  src/main/resources/images/healthemoticon.png
  src/main/resources/view/MainWindow.fxml
Labels: bug

#179 Edit PPP
  docs/team/joshruien.md
Labels: documentation

#180 updated PPP
  docs/team/yongmingyang.md
Labels: documentation

#175 Update PPP
  docs/team/johndoe.md
  docs/team/jonfoocy.md
Labels: documentation

#177 Update answer test GUI
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/ResultDisplay.fxml
Labels: GUI

#181 Quizcommandparser bug
  docs/UserGuide.md
  src/main/java/seedu/medmoriser/logic/commands/QuizCommand.java
  src/main/java/seedu/medmoriser/logic/parser/EditCommandParser.java
  src/main/java/seedu/medmoriser/logic/parser/QuizCommandParser.java
Labels: bug

#183 Remove status bar footer
  src/main/java/seedu/medmoriser/ui/MainWindow.java
Labels: GUI

#184 quiz command bug
  src/main/java/seedu/medmoriser/logic/commands/QuizCommand.java
Labels: bug

#185 Edit BetterModelClassDiagram
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/style.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/StorageClassDiagram.png
Labels: Developer's Guide

#182 added Add feature
  docs/DeveloperGuide.md
  docs/images/AddSequenceDiagram.png
  docs/images/ArchitectureDiagram.png
  docs/team/chengjiyuqing.md
Labels: Developer's Guide

#186 Fix find command
  src/main/java/seedu/medmoriser/logic/commands/FindCommand.java
  src/main/java/seedu/medmoriser/logic/parser/FindCommandParser.java
  src/test/java/seedu/medmoriser/logic/parser/FindCommandParserTest.java
Labels: bug

#188 minor tweak in PPP
  docs/team/yongmingyang.md
Labels: documentation

#187 update UG screenshots
  docs/UserGuide.md
  docs/images/AddCommandEg1.png
  docs/images/AddCommandEg2.png
  docs/images/DeleteContext.png
  docs/images/DeleteResult.png
  docs/images/EditContext.png
  docs/images/EditResult.png
  docs/images/FindContext.PNG
  docs/images/FindResult.PNG
  docs/images/ListCommand.png
  docs/images/ListQuestionsCommand.png
  docs/images/NextContext.png
  docs/images/NextResult.png
  docs/images/QuizContext.png
  docs/images/QuizResult.png
  docs/team/joshruien.md
Labels: User Guide

#191 Update UG screenshots
  docs/UserGuide.md
Labels: User Guide

#192 Fix typo in UG
  docs/UserGuide.md
Labels: User Guide

#193 update ug
  docs/UserGuide.md
  docs/images/FindContext.PNG
Labels: User Guide
